"""First

Revision ID: 250e3bec84b0
Revises: 
Create Date: 2021-08-27 16:40:12.896221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250e3bec84b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
